package com.nexhire.service;

import com.nexhire.enums.FileCategory;
import org.springframework.web.multipart.MultipartFile;

/**
 * Storage abstraction so the backing implementation (DB BYTEA today, filesystem/cloud
 * object storage later) can change without touching callers.
 */
public interface FileStorageService {

    /** Stores the file and returns the generated StoredFile id. */
    Long store(MultipartFile file, FileCategory category, Long uploadedByUserId);

    /** Stores system-generated bytes (e.g. an auto-generated PDF) not backed by a MultipartFile. */
    Long storeGenerated(byte[] data, String fileName, String contentType, FileCategory category, Long uploadedByUserId);

    StoredFileData retrieve(Long storedFileId);

    void delete(Long storedFileId);

    record StoredFileData(String fileName, String fileType, byte[] data) {
    }
}
